server:
  port: 90
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.165:8848
    gateway:
      routes:
        - id: coupon-route
          uri: lb://coupon-server/
          predicates:
            - Method=GET
            - Path=/coupon/**